# Unbind the default Ctrl+B prefix
unbind C-b

# Set the new prefix to Ctrl+A
set-option -g prefix C-a
bind-key C-a last-window
bind-key  a send-prefix

# Set cut-n-paste to screen mode
bind-key Escape copy-mode
bind-key -T copy-mode Enter send -X screen-enter

# set the status line off
set-option -g status off

# set the alert for bells
set-window-option -g monitor-bell on
set-option -g bell-action other
set-option -g visual-bell on

# stop eating the whole screen
bind-key w display-message -d 3000 '#{W:#{window_index}#{window_flags}:#{window_name} }'
